apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: my-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      topologySpreadConstraints:             #Поды с меткой foo: bar должны быть размещены относительно topologyKey: zone
      - maxSkew: 2                           #c максимальным отклонением maxSkew=1
        topologyKey: zone                    # т.е. не более 2х подов на каждое уникальное значение лейбла ноды zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu:  100m
            memory: 128Mi
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  # тип ресурса, который будем масштабировать
    name: my-service  # имя
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu # метрика, которую отслеживаем
      target:
        type: Utilization
        averageUtilization: 50  #порог срабатывания
